version: '3.8'

services:
  # sonarqube:
  #   image: sonarqube:lts
  #   container_name: sonarqube
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - sonar_data:/opt/sonarqube/data
  #     - sonar_extensions:/opt/sonarqube/extensions
  #     - sonar_logs:/opt/sonarqube/logs
  #     - sonar_conf:/opt/sonarqube/conf


# docker run -d --name sonarqube2 -p 9000:9000 -v 
# sonar_data:/opt/sonarqube/data 
# -v sonar_extensions:/opt/sonarqube/extensions -v sonar_logs:/opt/sonarqube/logs  -v sonar_conf:/opt/sonarqube/conf sonarqube:lts

  # Service Frontend React (Développement)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5001
    volumes:
      # Montage pour le hot-reload en développement
      - ./src:/app/src
      - ./public:/app/public
    stdin_open: true
    tty: true
    restart: unless-stopped

  # Service Backend Express
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - SESSION_SECRET=${SESSION_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - VM_IP=${VM_IP}
      - SSH_KEY=${SSH_KEY}
      - SONAR_HOST_URL=http://sonarqube:9000
      - SONAR_PROJECT_KEY=projet-pcs-backend
      - SONAR_TOKEN=sqp_97b878cd2abbeff483435bcb0dcadb0e5b3f89be
    volumes:
      # Monter le socket Docker pour permettre au backend d'utiliser Docker
      - /var/run/docker.sock:/var/run/docker.sock
      # Monter le dossier workspace
      - ./workspace:/app/workspace
      # Monter la clé SSH privée avec passphrase
      - ./.ssh/id_deploy_tp:/tmp/id_deploy_tp:ro
      # Monter la clé SSH privée avec passphrase
      - ./backend/.env:/app/.env
    restart: unless-stopped
    command: sh -c "cp /tmp/id_deploy_tp /root/.ssh/id_deploy_tp && chmod 600 /root/.ssh/id_deploy_tp && node server.js"

# volumes:
  # sonar_data:
  # sonar_extensions:
  # sonar_logs:
  # sonar_conf:

